Repository 42Heroes/42WLE-Back, pull requests merged in 2022-08, with the labels that each got.

#14 WE-212-refresh-token-set-cookie-same-site-변경
  src/auth/auth.controller.ts
Labels: Bug 🚨, High 🥇

#15 deleteBoardComment 수정
  src/board/board.controller.ts
  src/board/board.service.ts
  src/events/events.service.ts
  src/schemas/board/board.schema.ts
Labels: enhancement ✨, High 🥇

#16 UpdateUserDto에서_imageUrl_필드삭제
  src/user/dto/update-user.dto.ts
Labels: Bug 🚨, High 🥇

#18 WE-225 회원가입 로그인
  src/auth/auth.service.ts
  src/auth/dto/fortyTwo.dto.ts
  src/auth/fortyTwo.strategy.ts
  src/user/user.service.ts
Labels: Medium 🥈

#19 WE-236 fix board add / remove like
  src/board/board.service.ts
  src/schemas/board/board.schema.ts
Labels: Bug 🚨, Medium 🥈

#20 WE-232 Socket
  src/auth/auth.guard.ts
  src/events/events.gateway.ts
  src/events/events.service.ts
Labels: Medium 🥈
