Repository 42Heroes/42WLE-Back, pull requests merged in 2022-07, with the labels that each got.

#4 JWT 환경변수 적용
  src/auth/auth.module.ts
  src/events/events.service.ts
Labels: Medium 🥈

#7 WE-124 web rtc
  src/events/event.enum.ts
  src/events/events.gateway.ts
  src/events/roomMap.ts
Labels: enhancement ✨, High 🥇

#12 WE-210 likeUser api 변경
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: Refactor 🌈

#13 deleteBoard에서 author.save() 삭제
  src/board/board.controller.ts
  src/board/board.service.ts
Labels: Bug 🚨, High 🥇
